#!/usr/bin/env python3

import subprocess
import sys
from argparse import ArgumentParser

parser = ArgumentParser()
parser.add_argument(
    '-c',
    '--check-only',
    action='store_true',
    help='Perform checks without modifying files',
)
parser.add_argument('--install', action='store_true', help='Install tools')


def install(*packages, upgrade=True):
    args = [sys.executable, '-m', 'pip', 'install']
    if upgrade:
        args.append('-U')
    args.extend(packages)
    subprocess.run(args)


def run_isort(directory='.', *, check_only=False):
    print("# Running isort")
    args = ['isort', directory, __file__]
    if check_only:
        args.append('--check-only')
    subprocess.run(args, check=True)


def run_black(directory='.', *, check_only=False):
    print("# Running black")
    args = ['black', directory, __file__]
    if check_only:
        args.append('--check')
    subprocess.run(args, check=True)


def run_flake8(directory='.'):
    print("# Running flake8")
    subprocess.run(['flake8', directory, __file__], check=True)


def run_mypy():
    print("# Running mypy")
    subprocess.run(['mypy', '-p', 'replicat'], check=True)


if __name__ == '__main__':
    args = parser.parse_args()

    if args.install:
        install('isort', 'black', 'flake8', 'mypy', 'types-tqdm', upgrade=True)

    run_isort(check_only=args.check_only)
    run_black(check_only=args.check_only)
    run_flake8()
    run_mypy()
