name: Test
on: push

jobs:
  build:
    uses: ./.github/workflows/build.yml
  
  test:
    needs: build
    runs-on: windows-latest
    steps: 
      - run: python -m pip install `ls dist/*.whl`[test]
        shell: bash
      - run: python -m pytest --pyargs replicat
